# Generated by Django 6.0 on 2026-05-28 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Nazwa ikony lub emoji', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_limit_hours', models.IntegerField(default=24, help_text='How many hours before start cancellation is free')),
                ('base_hour_price', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('base_day_price', models.DecimalField(decimal_places=2, default=350.0, max_digits=6)),
                ('max_active_reservations', models.IntegerField(default=3, help_text='Maximum number of active reservations per user')),
                ('max_reservation_days', models.IntegerField(default=7, help_text='Maximum length of one reservation in days')),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='garages/')),
                ('description', models.TextField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, help_text='Width in meters', null=True)),
                ('length', models.FloatField(blank=True, help_text='Length in meters', null=True)),
                ('height', models.FloatField(blank=True, help_text='Height in meters', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('equipment', models.ManyToManyField(blank=True, to='garages.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Canceled'), ('completed', 'Completed'), ('expired', 'Expired (No payment)')], default='pending', max_length=20)),
                ('access_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_historical', models.BooleanField(default=False)),
                ('overstayed', models.BooleanField(default=False, help_text='Did the customer stay in the garage after the reservation time?')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Cancellation reason provided by admin', null=True)),
                ('cancellation_seen', models.BooleanField(default=False, help_text='Has the user read the cancellation notification?')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='garages.garage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_refunded', models.BooleanField(default=False)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='garages.reservation')),
            ],
        ),
    ]
