# Generated by Django 6.0 on 2026-05-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='base_day_price',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='base_hour_price',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=6),
        ),
    ]
